### ISSUE TITLE
Can you help upload this library to pypi?

### ISSUE THREAD

**Issue by artikell** [natoscott/valkey-module-test#1]
I am unable to install through pip. Perhaps you can help support uploading it

**Comment by natoscott** [comment]
This repo lives here for now (I'll close this fork shortly)...
https://github.com/goodform/valkey-module-test/

Do you need this python module for one of the modules there (Valkey modules on goodform org) or your own Valkey module?  pip is quite an involved process (we'd need to replace setup.py nowadays), and there is talk from Madelyn of producing a common test harness, so I had been thinking of using an embedded git-subtree in the 'standard' goodform modules until that's resolved (its possible a pip upload is a bit premature as more discussion is planned).

**Comment by artikell** [comment]
Great, I have created a new [template project](https://github.com/artikell/valkey-module-template) for future module projects. It depends on this project. It seems that Goodform is a great project. I'm not sure if this template project can be added

**Comment by natoscott** [comment]
@artikell that's awesome - I've sent through an invitation for you to join the org if you like, feel free to add the new template repo there.

**Comment by artikell** [comment]
Thank you very much, I have already completed it. I think there is still a lot of work to be done, and I'm not sure if Valkey has the energy to push it forward. I have thought about several directions: more modules (CPC Roaring bitmaps, vectors, etc.), more automated processes, and more user-friendly documents. Even legal issues, although I am not very familiar with them.
